// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitoSwimPT.Server.Models;

#nullable disable

namespace VitoSwimPT.Server.Migrations
{
    [DbContext(typeof(SwimContext))]
    [Migration("20251020093743_RefreshToken")]
    partial class RefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VitoSwimPT.Server.AllenamentiUtente.AllenamentoUtente", b =>
                {
                    b.Property<int>("AllenamentoUtenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllenamentoUtenteId"));

                    b.Property<int>("AllenamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateDone")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePlanned")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoneBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("UpdateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("AllenamentoUtenteId");

                    b.HasIndex("AllenamentoId");

                    b.HasIndex("DoneBy");

                    b.ToTable("AllenamentiUtente");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Models.Allenamento", b =>
                {
                    b.Property<int>("AllenamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllenamentoId"));

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeAllenamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AllenamentoId");

                    b.ToTable("Allenamenti");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Models.Esercizio", b =>
                {
                    b.Property<int>("EsercizioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EsercizioId"));

                    b.Property<int>("Distanza")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Recupero")
                        .HasColumnType("int");

                    b.Property<int>("Ripetizioni")
                        .HasColumnType("int");

                    b.Property<int>("StileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EsercizioId");

                    b.ToTable("Esercizi");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Models.EsercizioAllenamento", b =>
                {
                    b.Property<int>("EsercizioId")
                        .HasColumnType("int");

                    b.Property<int>("AllenamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EsercizioId", "AllenamentoId");

                    b.ToTable("EserciziAllenamenti");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Models.Piano", b =>
                {
                    b.Property<int>("PianoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PianoId"));

                    b.Property<Guid>("Createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomePiano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PianoId");

                    b.HasIndex("Createdby");

                    b.ToTable("Piani");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Models.PianoAllenamento", b =>
                {
                    b.Property<int>("PianoId")
                        .HasColumnType("int");

                    b.Property<int>("AllenamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PianoId", "AllenamentoId");

                    b.ToTable("PianiAllenamento");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Models.Stile", b =>
                {
                    b.Property<int>("StileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StileId"));

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StileId");

                    b.ToTable("Stili");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Users.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("VitoSwimPT.Server.AllenamentiUtente.AllenamentoUtente", b =>
                {
                    b.HasOne("VitoSwimPT.Server.Models.Allenamento", "Allenamento")
                        .WithMany()
                        .HasForeignKey("AllenamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitoSwimPT.Server.Users.User", "Utente")
                        .WithMany()
                        .HasForeignKey("DoneBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allenamento");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Models.Piano", b =>
                {
                    b.HasOne("VitoSwimPT.Server.Users.User", "Utente")
                        .WithMany()
                        .HasForeignKey("Createdby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Users.EmailVerificationToken", b =>
                {
                    b.HasOne("VitoSwimPT.Server.Users.User", "Utente")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("VitoSwimPT.Server.Users.RefreshToken", b =>
                {
                    b.HasOne("VitoSwimPT.Server.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
